version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smart_factory_postgres
    environment:
      POSTGRES_USER: factory_user
      POSTGRES_PASSWORD: factory_pwd
      POSTGRES_DB: factory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
